# sonarqube.yml
name: SonarQube Quality Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ensure gradlew has execute permissions
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Run tests with Gradle
      - name: Run tests
        run: ./gradlew test

      # Run SonarQube analysis (configure your SonarQube token)
      - name: Run SonarQube Analysis
        run: ./gradlew sonarqube -Dsonar.projectKey=my-project-key -Dsonar.host.url=http://your-sonarqube-url -Dsonar.login=$SONARQUBE_TOKEN
